import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { AdminLayout } from "@/components/layout/AdminLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  useGetAdminSession,
  useGetAiInsights,
  useAskAi,
  getGetAdminSessionQueryKey,
  getGetAiInsightsQueryKey,
} from "@workspace/api-client-react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { motion } from "framer-motion";
import {
  Sparkles,
  Loader2,
  RefreshCw,
  MapPin,
  TrendingUp,
  TrendingDown,
  Minus,
  AlertTriangle,
  Building2,
  Send,
  Bot,
  ArrowRightCircle,
  ShieldAlert,
  LayoutGrid,
  Users,
} from "lucide-react";

function riskColor(risk: string) {
  switch (risk) {
    case "Critical":
      return "bg-red-50 text-red-700 border-red-200";
    case "High":
      return "bg-orange-50 text-orange-700 border-orange-200";
    case "Medium":
      return "bg-amber-50 text-amber-700 border-amber-200";
    default:
      return "bg-slate-50 text-slate-600 border-slate-200";
  }
}

function priorityColor(priority: string) {
  switch (priority) {
    case "Urgent":
      return "bg-red-50 text-red-700 border-red-200";
    case "High":
      return "bg-orange-50 text-orange-700 border-orange-200";
    case "Medium":
      return "bg-amber-50 text-amber-700 border-amber-200";
    default:
      return "bg-slate-50 text-slate-600 border-slate-200";
  }
}

function SectionCard({
  title,
  icon: Icon,
  children,
}: {
  title: string;
  icon: React.ElementType;
  children: React.ReactNode;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white border rounded-xl p-5 shadow-sm"
    >
      <div className="flex items-center gap-2 mb-4">
        <Icon className="h-4 w-4 text-primary" />
        <h2 className="text-sm font-semibold text-slate-900">{title}</h2>
      </div>
      {children}
    </motion.div>
  );
}

export default function AiDashboard() {
  const [, setLocation] = useLocation();
  const { data: session, isLoading: sessionLoading } = useGetAdminSession({
    query: { queryKey: getGetAdminSessionQueryKey(), retry: false },
  });

  useEffect(() => {
    if (!sessionLoading && (!session || !session.authenticated)) {
      setLocation("/admin/login");
    }
  }, [session, sessionLoading, setLocation]);

  const {
    data: insights,
    isLoading,
    isFetching,
    isError,
    error,
    refetch,
  } = useGetAiInsights(undefined, {
    query: {
      queryKey: getGetAiInsightsQueryKey(),
      enabled: !sessionLoading && Boolean(session?.authenticated),
      staleTime: 5 * 60 * 1000,
      retry: false,
    },
  });

  const askAi = useAskAi();
  const [question, setQuestion] = useState("");
  const [conversation, setConversation] = useState<Array<{ role: "user" | "ai"; text: string }>>([]);

  const handleAsk = () => {
    const trimmed = question.trim();
    if (!trimmed || askAi.isPending) return;
    setConversation((prev) => [...prev, { role: "user", text: trimmed }]);
    setQuestion("");
    askAi.mutate(
      { data: { question: trimmed } },
      {
        onSuccess: (res) => {
          setConversation((prev) => [...prev, { role: "ai", text: res.answer }]);
        },
        onError: () => {
          setConversation((prev) => [
            ...prev,
            { role: "ai", text: "Sorry, the AI assistant is unavailable right now. Please try again shortly." },
          ]);
        },
      },
    );
  };

  if (sessionLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <AdminLayout>
      <div className="p-6 space-y-6 overflow-auto">
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div>
            <h1 className="text-xl font-bold text-slate-900 flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" />
              AI Decision Dashboard
            </h1>
            <p className="text-sm text-slate-500">
              AI-powered analysis of complaint data — grounded in real records, generated by Gemini
              {insights?.cached ? " · cached" : ""}
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={() => refetch()} disabled={isFetching}>
            <RefreshCw className={`h-4 w-4 mr-2 ${isFetching ? "animate-spin" : ""}`} />
            Refresh insights
          </Button>
        </div>

        {isLoading ? (
          <div className="py-24 flex flex-col items-center justify-center text-slate-400 gap-3">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-sm">Analyzing complaint data with AI...</p>
          </div>
        ) : isError || !insights ? (
          <div className="bg-white border rounded-xl p-8 text-center space-y-2">
            <AlertTriangle className="h-8 w-8 text-amber-500 mx-auto" />
            <p className="text-sm font-medium text-slate-700">AI insights are unavailable right now.</p>
            <p className="text-xs text-slate-500">
              {(error as { message?: string } | undefined)?.message ??
                "This can happen if the AI service is temporarily down or not configured. Please try again shortly."}
            </p>
            <Button size="sm" onClick={() => refetch()} className="mt-2">
              Try again
            </Button>
          </div>
        ) : (
          <>
            {/* AI Summary */}
            <SectionCard title="AI Complaint Summary" icon={Bot}>
              <p className="text-sm text-slate-700 leading-relaxed">{insights.summary}</p>
            </SectionCard>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Recommendations */}
              <SectionCard title="AI Recommendations" icon={ArrowRightCircle}>
                {insights.recommendations.length > 0 ? (
                  <ul className="space-y-2">
                    {insights.recommendations.map((rec, i) => (
                      <li key={i} className="text-sm text-slate-700 flex gap-2">
                        <span className="text-primary font-bold">•</span>
                        {rec}
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-sm text-slate-400">No recommendations available.</p>
                )}
              </SectionCard>

              {/* Predictions */}
              <SectionCard title="Predictive Analytics" icon={TrendingUp}>
                <p className="text-sm text-slate-700 leading-relaxed mb-3">{insights.predictions}</p>
                <div className="flex items-center gap-2 text-xs">
                  <span className="text-slate-500">Trend direction:</span>
                  {insights.trend.direction === "up" ? (
                    <span className="flex items-center gap-1 text-red-600 font-medium">
                      <TrendingUp className="h-3.5 w-3.5" /> Increasing
                    </span>
                  ) : insights.trend.direction === "down" ? (
                    <span className="flex items-center gap-1 text-green-600 font-medium">
                      <TrendingDown className="h-3.5 w-3.5" /> Decreasing
                    </span>
                  ) : (
                    <span className="flex items-center gap-1 text-slate-600 font-medium">
                      <Minus className="h-3.5 w-3.5" /> Stable
                    </span>
                  )}
                  <span className="text-slate-500">
                    · Forecast next month: <span className="font-semibold text-slate-900">{insights.trend.forecastNextMonth}</span>
                  </span>
                </div>
              </SectionCard>
            </div>

            {/* Trend Chart */}
            <SectionCard title="Trend Analysis" icon={TrendingUp}>
              {insights.trend.monthly.length > 0 ? (
                <ResponsiveContainer width="100%" height={220}>
                  <LineChart data={insights.trend.monthly} margin={{ top: 5, right: 10, bottom: 5, left: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                    <XAxis dataKey="month" tick={{ fontSize: 10 }} tickLine={false} />
                    <YAxis tick={{ fontSize: 10 }} tickLine={false} axisLine={false} />
                    <Tooltip />
                    <Line type="monotone" dataKey="count" stroke="#2563EB" strokeWidth={2} dot={false} />
                  </LineChart>
                </ResponsiveContainer>
              ) : (
                <div className="h-[220px] flex items-center justify-center text-slate-400 text-sm">No data yet</div>
              )}
            </SectionCard>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Hotspots */}
              <SectionCard title="Hotspot Detection" icon={MapPin}>
                {insights.hotspots.length > 0 ? (
                  <div className="space-y-2">
                    {insights.hotspots.map((h) => (
                      <div key={h.area} className="flex items-center justify-between border rounded-lg px-3 py-2">
                        <div>
                          <p className="text-sm font-medium text-slate-900">{h.area}</p>
                          <p className="text-xs text-slate-500">
                            {h.total} complaints · {h.pending} pending · top: {h.topCategory}
                          </p>
                        </div>
                        <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${riskColor(h.riskLevel)}`}>
                          {h.riskLevel}
                        </span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-slate-400">No hotspots detected yet.</p>
                )}
              </SectionCard>

              {/* Area-wise Analytics */}
              <SectionCard title="Area-wise Analytics" icon={LayoutGrid}>
                {insights.areaAnalytics.length > 0 ? (
                  <div className="overflow-auto max-h-64">
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="border-b bg-slate-50">
                          {["Area", "Total", "Pending", "In Progress", "Resolved", "Avg Pending Age"].map((h) => (
                            <th key={h} className="text-left px-2 py-2 font-medium text-slate-500">
                              {h}
                            </th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {insights.areaAnalytics.map((a) => (
                          <tr key={a.area} className="border-b last:border-0">
                            <td className="px-2 py-2 font-medium text-slate-900">{a.area}</td>
                            <td className="px-2 py-2 text-slate-600">{a.total}</td>
                            <td className="px-2 py-2 text-slate-600">{a.pending}</td>
                            <td className="px-2 py-2 text-slate-600">{a.inProgress}</td>
                            <td className="px-2 py-2 text-slate-600">{a.resolved}</td>
                            <td className="px-2 py-2 text-slate-600">{a.avgPendingAgeDays}d</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                ) : (
                  <p className="text-sm text-slate-400">No area data yet.</p>
                )}
              </SectionCard>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Priority Recommendations */}
              <SectionCard title="Priority Recommendations" icon={ShieldAlert}>
                {insights.priorityRecommendations.length > 0 ? (
                  <div className="space-y-2 max-h-64 overflow-auto">
                    {insights.priorityRecommendations.map((p) => (
                      <div key={p.complaintId} className="border rounded-lg px-3 py-2">
                        <div className="flex items-center justify-between">
                          <span className="font-mono text-xs text-primary">{p.complaintId}</span>
                          <div className="flex items-center gap-1.5 text-xs">
                            <span className={`px-2 py-0.5 rounded-full border ${priorityColor(p.currentPriority)}`}>{p.currentPriority}</span>
                            <ArrowRightCircle className="h-3.5 w-3.5 text-slate-400" />
                            <span className={`px-2 py-0.5 rounded-full border font-medium ${priorityColor(p.recommendedPriority)}`}>
                              {p.recommendedPriority}
                            </span>
                          </div>
                        </div>
                        <p className="text-xs text-slate-500 mt-1">
                          {p.area} · {p.category} — {p.reason}
                        </p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-slate-400">All complaints have appropriate priority.</p>
                )}
              </SectionCard>

              {/* Department Recommendation */}
              <SectionCard title="Department Recommendation" icon={Building2}>
                {insights.departmentMapping.length > 0 ? (
                  <div className="space-y-2">
                    {insights.departmentMapping.map((d) => (
                      <div key={d.category} className="flex items-center justify-between border rounded-lg px-3 py-2">
                        <div>
                          <p className="text-sm font-medium text-slate-900">{d.category}</p>
                          <p className="text-xs text-slate-500">{d.department}</p>
                        </div>
                        <span className="text-xs font-semibold text-slate-700 bg-slate-100 rounded-full px-2 py-0.5">
                          {d.count}
                        </span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-slate-400">No department data yet.</p>
                )}
              </SectionCard>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Severity Analysis */}
              <SectionCard title="AI Severity Analysis" icon={AlertTriangle}>
                {insights.severityAnalysis.length > 0 ? (
                  <div className="space-y-2 max-h-64 overflow-auto">
                    {insights.severityAnalysis.map((s) => (
                      <div key={s.complaintId} className="border rounded-lg px-3 py-2">
                        <div className="flex items-center justify-between">
                          <span className="font-mono text-xs text-primary">{s.complaintId}</span>
                          <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${riskColor(s.severity)}`}>
                            {s.severity}
                          </span>
                        </div>
                        <p className="text-xs text-slate-500 mt-1">{s.reason}</p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-slate-400">No elevated-severity complaints detected.</p>
                )}
              </SectionCard>

              {/* Pattern Detection & Similar Complaints */}
              <SectionCard title="Pattern & Similar-Complaint Detection" icon={Users}>
                {insights.patterns.length === 0 && insights.similarGroups.length === 0 ? (
                  <p className="text-sm text-slate-400">No recurring patterns detected yet.</p>
                ) : (
                  <div className="space-y-3 max-h-64 overflow-auto">
                    {insights.patterns.map((p, i) => (
                      <div key={i} className="border rounded-lg px-3 py-2">
                        <p className="text-sm font-medium text-slate-900">{p.title}</p>
                        <p className="text-xs text-slate-500">{p.description}</p>
                        <p className="text-xs text-slate-400 mt-1">
                          Related: {p.complaintIds.join(", ") || "—"}
                        </p>
                      </div>
                    ))}
                    {insights.similarGroups.map((g, i) => (
                      <div key={`sim-${i}`} className="border rounded-lg px-3 py-2 bg-slate-50">
                        <p className="text-xs font-medium text-slate-700">
                          Similar complaints: {g.complaintIds.join(", ")}
                        </p>
                        <p className="text-xs text-slate-500">{g.reason}</p>
                      </div>
                    ))}
                  </div>
                )}
              </SectionCard>
            </div>
          </>
        )}

        {/* Ask AI */}
        <SectionCard title="Ask AI" icon={Sparkles}>
          <p className="text-xs text-slate-500 mb-3">
            Ask a question about complaints in natural language — answers are grounded only in real data.
          </p>
          {conversation.length > 0 && (
            <div className="space-y-2 mb-3 max-h-64 overflow-auto">
              {conversation.map((m, i) => (
                <div
                  key={i}
                  className={`text-sm rounded-lg px-3 py-2 max-w-[90%] ${
                    m.role === "user" ? "bg-primary/10 text-slate-900 ml-auto" : "bg-slate-50 text-slate-700"
                  }`}
                >
                  {m.text}
                </div>
              ))}
              {askAi.isPending && (
                <div className="bg-slate-50 text-slate-400 text-sm rounded-lg px-3 py-2 flex items-center gap-2 w-fit">
                  <Loader2 className="h-3.5 w-3.5 animate-spin" /> Thinking...
                </div>
              )}
            </div>
          )}
          <div className="flex gap-2">
            <Textarea
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              placeholder="e.g. Which areas have the most unresolved complaints this month?"
              className="min-h-[44px] resize-none"
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleAsk();
                }
              }}
            />
            <Button onClick={handleAsk} disabled={askAi.isPending || !question.trim()}>
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </SectionCard>
      </div>
    </AdminLayout>
  );
}
